name: Deploy from webhook

on:
  repository_dispatch:
    types: [test_result]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
